name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Запускать на основной ветке
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      MAJOR_VERSION: 1
      MINOR_VERSION: 0
      PATCH_VERSION: 1
      BUILD_NUMBER: ${{ github.run_number }} # Автоинкрементируемый номер билда
      IMAGE_NAME: taraskrupko/integrator-auth # Укажите ваш репозиторий и имя образа на Docker Hub

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Calculate version
        run: |
          # Формируем версию из мажорной, минорной и номера билда
          version="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
          echo "version=$version" >> $GITHUB_ENV
          echo "Собранная версия: $version"

          fullVersion="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}.${BUILD_NUMBER}"
          echo "fullVersion=$fullVersion" >> $GITHUB_ENV
          echo "Полная версия: $fullVersion"

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ env.version }} --build-arg VERSION=${{ env.fullVersion }} -f integrator_auth/Dockerfile .
          docker push $IMAGE_NAME:${{ env.version }}
